In [1]:
pip install numpy

In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [6]:
#McCulloh Pitt model for AND model
import numpy as np

def McAnd(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output

x0 = np.array([1,1,0])
x1 = np.array([0,1,0])
x2 = np.array([1,1,1])
x3 = np.array([1,0,1])
w = np.array([1,0,-1])

t = 0
ans1 = McAnd(x0,w,t)
print (x0, "value", ans1)
ans2 = McAnd(x1,w,t)
print (x1, "value", ans2)
ans3 = McAnd(x2,w,t)
print (x2, "value", ans3)
ans4 = McAnd(x3,w,t)
print (x3, "value", ans4)

[1 1 0] value 1
[0 1 0] value 0
[1 1 1] value 0
[1 0 1] value 0


In [7]:
#McCulloh Pitt model for OR model
import numpy as np

def McOr(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output
x0 = np.array([0,0,1])
x1 = np.array([0,1,1])
x2 = np.array([1,0,1])
x3 = np.array([1,1,1])
w = np.array([3,6,-1])
t = 0
ans1 = McOr(x0,w,t)
print (x0, "value", ans1)
ans2 = McOr(x1,w,t)
print (x1, "value", ans2)
ans3 = McOr(x2,w,t)
print (x2, "value", ans3)
ans4 = McOr(x3,w,t)
print (x3, "value", ans4)

[0 0 1] value 0
[0 1 1] value 1
[1 0 1] value 1
[1 1 1] value 1


In [8]:
#McCulloh Pitt model for NOT model
import numpy as np

def McNOT(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output
x0 = np.array([1,0])
x1 = np.array([0,1])
w = np.array([0,-1])
t = 0
ans1 = McNOT(x0,w,t)
print (x0, "value", ans1)
ans2 = McNOT(x1,w,t)
print (x1, "value", ans2)

[1 0] value 0
[0 1] value 0


In [10]:
#Matrix Addition

import numpy as np

A = np.array([[2,3,5],[6,-1,8],[-2,4,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-4,6,1]])
C = A+B
print(C)

[[ 8 -2  3]
 [11  6  4]
 [-6 10 10]]


In [12]:
#Matrix Subtraction

import numpy as np

A = np.array([[2,3,5],[6,-1,8],[-2,4,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-4,6,1]])
C = A-B
print(C)

[[-4  8  7]
 [ 1 -8 12]
 [ 2 -2  8]]


In [13]:
#Matrix Multiplication

import numpy as np

A = np.array([[2,3,5],[6,-1,8],[-2,4,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-4,6,1]])
C = A*B
print(C)

[[ 12 -15 -10]
 [ 30  -7 -32]
 [  8  24   9]]
